In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(r"C:\Projectos\Python-ETL\data\raw\RestaurantSales.xlsx")
df.head(10)

,Transaction ID,Order Date,Restaurant Location,Order Type,Menu Item,Category,Quantity,Unit Price,Order Total,Customer Rating
0,RST-30001,2024-07-05,Coral Gables,Delivery,Chicken Parmesan,Main,2,18.99,37.98,4
1,RST-30002,2024-09-22,Chicago Loop,Takeaway,House Wine,Beverage,1,9.99,9.99,4
2,RST-30003,2025-04-20,Midtown East,Takeaway,Soup of the Day,Appetizer,3,8.99,26.97,5
3,RST-30004,2024-06-28,Lincoln Park,Delivery,Sparkling Water,Beverage,2,3.49,6.98,5
4,RST-30005,2025-07-05,Austin South Congress,Dine-In,Craft Beer,Beverage,1,7.99,7.99,3
5,RST-30006,2025-05-15,Downtown Manhattan,Delivery,Soup of the Day,Appetizer,1,8.99,8.99,3
6,RST-30007,2024-05-26,Miami Beach,Dine-In,Chicken Parmesan,Main,1,18.99,18.99,4
7,RST-30008,2025-11-22,Downtown Manhattan,Takeaway,Mushroom Risotto,Main,2,16.99,33.98,4
8,RST-30009,2024-10-10,Upper West Side,Dine-In,Grilled Salmon,Main,3,24.99,74.97,4
9,RST-30010,2024-12-28,Austin South Congress,Dine-In,Caesar Salad,Appetizer,1,12.99,12.99,3

In [ ]:
# calc- localizar o 1 item especifico de uma coluna
df_cal = df.loc[df["Restaurant Location"] == 'Chicago Loop']

In [ ]:
df_cal

In [ ]:
itens = ['Austin South Congress', 'Upper West Side','Miami beach' ]
df_itens = df.loc[df['Restaurant Location'].isin(itens)]

In [ ]:
df_itens.head()

In [ ]:
# localizar valor > que o que escolher
dfMais100 = df.loc[df["Unit Price"] > 10]

In [ ]:
dfMais100.head()

In [18]:
df20a10 = df.loc[(df["Unit Price"] > 10) & (df["Unit Price"] < 20) ]

In [19]:
df20a10.head()

,Transaction ID,Order Date,Restaurant Location,Order Type,Menu Item,Category,Quantity,Unit Price,Order Total,Customer Rating
0,RST-30001,2024-07-05,Coral Gables,Delivery,Chicken Parmesan,Main,2,18.99,37.98,4
6,RST-30007,2024-05-26,Miami Beach,Dine-In,Chicken Parmesan,Main,1,18.99,18.99,4
7,RST-30008,2025-11-22,Downtown Manhattan,Takeaway,Mushroom Risotto,Main,2,16.99,33.98,4
9,RST-30010,2024-12-28,Austin South Congress,Dine-In,Caesar Salad,Appetizer,1,12.99,12.99,3
10,RST-30011,2025-05-09,Coral Gables,Dine-In,Bruschetta,Appetizer,2,11.99,23.98,5