In [ ]:
import pandas as pd

In [19]:
df = pd.read_csv(r"C:\Projectos\Python-ETL\data\raw\EmployeeRH.csv", delimiter=';')
df.head(10)

,Employee ID,Full Name,Gender,Department,Job Title,Hire Date,Annual Salary,Performance Rating,Satisfaction Score,Employment Status
0,EMP-1001,Richard Hernandez,Male,Sales,Sales Representative,02/12/2023,$85 100,2,3,Active
1,EMP-1002,Richard Harris,Male,Operations,Warehouse Supervisor,11/04/2020,$54 900,5,6,Active
2,EMP-1003,Timothy Rodriguez,Male,Sales,Sales Representative,10/06/2017,$80 200,4,5,Active
3,EMP-1004,Amanda Young,Female,Marketing,Marketing Coordinator,03/09/2018,$63 300,4,6,Active
4,EMP-1005,Nancy Clark,Female,Finance,Financial Analyst,04/28/2016,$61 400,3,3,Resigned
5,EMP-1006,William Williams,Male,Engineering,Software Engineer,01/31/2018,$101 800,4,5,Active
6,EMP-1007,Laura Garcia,Female,Engineering,QA Analyst,01/31/2021,$86 300,4,6,Resigned
7,EMP-1008,Mary Jackson,Female,Customer Support,Technical Support Specialist,10/08/2017,$59 000,2,2,Resigned
8,EMP-1009,Laura Allen,Female,Marketing,Brand Manager,12/28/2015,$120 900,3,4,Active
9,EMP-1010,Stephanie Lee,Female,Operations,Process Improvement Lead,02/07/2023,$78 600,3,3,Active

In [29]:
#filtrar 1 item especifico de uma coluna
departament = df.loc[df['Department'] == 'Finance']
departament.head()

,Employee ID,Full Name,Gender,Department,Job Title,Hire Date,Annual Salary,Performance Rating,Satisfaction Score,Employment Status
4,EMP-1005,Nancy Clark,Female,Finance,Financial Analyst,04/28/2016,$61 400,3,3,Resigned
16,EMP-1017,Mary Walker,Female,Finance,Financial Analyst,08/27/2016,$81 200,5,8,Active
24,EMP-1025,George Hernandez,Male,Finance,Accountant,03/22/2023,$60 600,4,6,Active
36,EMP-1037,Matthew Brown,Male,Finance,Budget Manager,04/06/2021,$142 900,4,8,Active
38,EMP-1039,Ashley Lewis,Female,Finance,Budget Manager,09/28/2021,$95 900,4,6,Active

In [33]:
# Número de departamentos 
len(departament)

137

In [28]:
# escolher departamento específicos
departaments = ['Sales','Operation','Marketing','Engineering']
#Filtrar apenas as linhas onde o departamento está na lista
df_departaments = df.loc[df['Department'].isin(departaments)]
df_departaments.head()

,Employee ID,Full Name,Gender,Department,Job Title,Hire Date,Annual Salary,Performance Rating,Satisfaction Score,Employment Status
0,EMP-1001,Richard Hernandez,Male,Sales,Sales Representative,02/12/2023,$85 100,2,3,Active
2,EMP-1003,Timothy Rodriguez,Male,Sales,Sales Representative,10/06/2017,$80 200,4,5,Active
3,EMP-1004,Amanda Young,Female,Marketing,Marketing Coordinator,03/09/2018,$63 300,4,6,Active
5,EMP-1006,William Williams,Male,Engineering,Software Engineer,01/31/2018,$101 800,4,5,Active
6,EMP-1007,Laura Garcia,Female,Engineering,QA Analyst,01/31/2021,$86 300,4,6,Resigned